### ISSUE TITLE
Some docstrings are not correctly rendered in the documentation

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaDiagnostics.jl#65]
- [x] `Missing docstring for ClimaDiagnostics.DiagnosticVariables.long_name. Check Documenter's build log for details.`
- [x] file:///home/sbozzolo/repos/ClimaDiagnostics.jl/docs/build/writers.html
- [x] broken link in docs "User Guide" page, [Schedules section](https://clima.github.io/ClimaDiagnostics.jl/dev/user_guide/#Schedules) - link to `Schedules` near bottom of section

**Comment by juliasloan25** [comment]
A couple of other comments I had -
- The [NetCDF writer section](https://clima.github.io/ClimaDiagnostics.jl/dev/writers/#NetCDFWriter) describes the inputs in words, but it isn't clear looking at the docs what's required vs optional
  - e.g. this section talks about regridding, but I imagine a common use case is saving files without any regridding. A minimal example showing how to save to netCDF without any regridding could be helpful
- A usage example of `orchestrate_diagnostics` would be helpful - I couldn't find the interface in the docs (maybe this is because it's meant to be an internal function, but if it ends up being used by users sometimes, more info would be nice)
